ALTER TABLE analytics_session ADD COLUMN entry_page_title VARCHAR(512);
ALTER TABLE analytics_session ADD COLUMN exit_page_title VARCHAR(512);

CREATE TABLE analytics_page_title_daily (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  site_id UUID NOT NULL REFERENCES site(id) ON DELETE CASCADE,
  business_date DATE NOT NULL,
  path VARCHAR(2048) NOT NULL,
  title VARCHAR(512) NOT NULL DEFAULT '',
  page_view_count BIGINT NOT NULL CHECK (page_view_count >= 0)
);

CREATE INDEX analytics_page_title_daily_site_date_idx ON analytics_page_title_daily(site_id,business_date);
