FROM quay.io/quarkus/quarkus-micro-image:2.0

WORKDIR /work/

COPY --chown=1001:root --chmod=0755 server/build/*-runner /work/application

EXPOSE 8080
USER 1001

ENTRYPOINT ["./application", "-Dquarkus.http.host=0.0.0.0"]
